create table
  public.potions_inventory (
    potion_id integer generated by default as identity not null,
    inventory integer null default 0,
    sku text null,
    price integer null,
    potion_type integer[] null,
    constraint potion_pkey primary key (potion_id)
  ) tablespace pg_default;

  create table
  public.global_inventory (
    id bigint generated by default as identity not null,
    num_green_ml integer null default 0,
    gold integer null default 100,
    num_red_ml integer null default 0,
    num_blue_ml integer null default 0,
    num_dark_ml integer null default 0,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.customers (
    id bigint generated by default as identity not null,
    customer_name character varying null,
    customer_class character varying null,
    level integer null,
    constraint customer_pkey primary key (id),
    constraint unique_customer_name unique (customer_name)
  ) tablespace pg_default;

  create table
  public.carts (
    id bigint generated by default as identity not null,
    customer_id integer null,
    created_at timestamp with time zone not null default now(),
    constraint cart_pkey primary key (id),
    constraint cart_customer_id_fkey foreign key (customer_id) references customers (id)
  ) tablespace pg_default;

  create table
  public.cart_items (
    id bigint generated by default as identity not null,
    qty integer not null default 0,
    cart_id bigint null,
    potion_id bigint null,
    added_at timestamp with time zone not null default (now() at time zone 'utc'::text),
    constraint cart_items_pkey primary key (id),
    constraint unique_cart_potion unique (cart_id, potion_id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (id),
    constraint cart_items_potion_id_fkey foreign key (potion_id) references potions_inventory (potion_id)
  ) tablespace pg_default;