create table
  public.potions_inventory (
    potion_id integer generated by default as identity not null,
    sku text null,
    price integer null,
    potion_type integer[] null,
    potion_name text null default 'NULL'::text,
    num_red_ml integer null default 0,
    num_green_ml integer null default 0,
    num_blue_ml integer null default 0,
    num_dark_ml integer null default 0,
    constraint potion_pkey primary key (potion_id)
  ) tablespace pg_default;

create table
  public.potion_ledger (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    potion_id integer null default 0,
    potion_change bigint null default '0'::bigint,
    constraint potion_ledger_pkey primary key (id),
    constraint potion_ledger_potion_id_fkey foreign key (potion_id) references potions_inventory (potion_id)
  ) tablespace pg_default;

create table
  public.ml_ledger (
    id bigint generated by default as identity not null,
    red_ml_change bigint null default '0'::bigint,
    green_ml_change bigint null default '0'::bigint,
    blue_ml_change bigint null default '0'::bigint,
    dark_ml_change bigint null default '0'::bigint,
    wrong_created_at time without time zone not null default now(),
    created_at timestamp with time zone null default (now() at time zone 'utc'::text),
    constraint ml_ledge_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.potion_c_ledger (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    potion_c_change integer null default 0,
    constraint potion_c_ledger_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.ml_c_ledger (
    id bigint generated by default as identity not null,
    ml_c_change integer null default 0,
    created_at timestamp with time zone not null default now(),
    constraint ml_c_ledger_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.gold_ledger (
    id bigint generated by default as identity not null,
    gold_change integer null default 0,
    created_at timestamp with time zone not null default now(),
    constraint gold_ledger_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.customers (
    id bigint generated by default as identity not null,
    customer_name character varying null,
    customer_class character varying null,
    level integer null,
    constraint customer_pkey primary key (id),
    constraint unique_customer_name unique (customer_name)
  ) tablespace pg_default;

create table
  public.capacities (
    id bigint generated by default as identity not null,
    potion_c bigint null default '10000'::bigint,
    ml_c bigint null default '50'::bigint,
    buy_potion_c boolean null default false,
    buy_ml_c boolean null default false,
    constraint capacities_pkey primary key (id)
  ) tablespace pg_default;
  
  create table
  public.carts (
    id bigint generated by default as identity not null,
    customer_id integer null,
    created_at timestamp with time zone not null default now(),
    constraint cart_pkey primary key (id),
    constraint cart_customer_id_fkey foreign key (customer_id) references customers (id)
  ) tablespace pg_default;

  create table
  public.cart_items (
    id bigint generated by default as identity not null,
    qty integer not null default 0,
    cart_id bigint null,
    potion_id bigint null,
    added_at timestamp with time zone not null default (now() at time zone 'utc'::text),
    constraint cart_items_pkey primary key (id),
    constraint unique_cart_potion unique (cart_id, potion_id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (id),
    constraint cart_items_potion_id_fkey foreign key (potion_id) references potions_inventory (potion_id)
  ) tablespace pg_default;